# Generated by Django 4.1.1 on 2025-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0012_alter_location_locid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC31886", editable=False, max_length=50, unique=True
            ),
        ),
    ]
