# Generated by Django 4.1.1 on 2025-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0015_alter_location_locid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC10297", editable=False, max_length=50, unique=True
            ),
        ),
    ]
