# Generated by Django 4.1.1 on 2025-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0016_alter_location_locid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC28417", editable=False, max_length=50, unique=True
            ),
        ),
    ]
