# Generated by Django 4.1.1 on 2025-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_app', '0017_alter_location_locid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locId',
            field=models.CharField(default='LOC28634', editable=False, max_length=50, unique=True),
        ),
    ]
