# Generated by Django 4.1.1 on 2025-05-31 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sensor_app", "0020_sensor_user_alter_location_locid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC40775", editable=False, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sensors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
