# Generated by Django 4.1.1 on 2025-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor_app", "0021_alter_location_locid_alter_sensor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="locId",
            field=models.CharField(
                default="LOC54477", editable=False, max_length=50, unique=True
            ),
        ),
    ]
